import { Metadata } from "next"

export const metadata: Metadata = {
  title: 'API - CRUD',
  description: 'Generated by Next.js',
  keywords: 'API, CRUD, Next.js',
  authors: {name: 'Edinson Madrid'},
  icons:{
    icon: '/favicon.ico',
    shortcut: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
